services:
  - type: web
    name: skillswap
    env: node
    rootDir: .
    buildCommand: "npm install --prefix Frontend && npm run build --prefix Frontend && npm install --prefix Backend"
    startCommand: "node Backend/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      # - key: MAIL_USER
      #   sync: false
      # - key: MAIL_PASS
      #   sync: false
